application: just-too-easy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /players.*
  script: players.app

- url: /shot_types.*
  script: shot_types.app

- url: /game.*
  script: game.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
