runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts

- url: /players.*
  script: controllers.players.app

- url: /game.*
  script: controllers.game.app

- url: /api.*
  script: controllers.api.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
