application: just-too-easy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts

- url: /players.*
  script: controllers.players.app

- url: /shot_types.*
  script: controllers.shot_types.app

- url: /game.*
  script: controllers.game.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
